### ISSUE TITLE
Failing build with ubuntu:20.04

### ISSUE THREAD

**Issue by dlemstra** [aous72/OpenJPH#295]
This project no longer builds with `ubuntu:20.04` and now reports the following error:
```
0.734 [  7%] Building CXX object src/core/CMakeFiles/openjph.dir/codestream/ojph_codestream_local.cpp.o
0.814 /OpenJPH/src/core/codestream/ojph_codestream_local.cpp: In member function 'void ojph::local::codestream::write_headers(ojph::outfile_base*, const ojph::comment_exchange*, ojph::ui32)':
0.814 /OpenJPH/src/core/codestream/ojph_codestream_local.cpp:643:49: error: call of overloaded 'swap_bytes_if_le(ojph::local::JP2K_MARKER)' is ambiguous
0.814   643 |       ui16 t = swap_bytes_if_le(JP2K_MARKER::SOC);
0.814       |                                                 ^
0.814 In file included from /OpenJPH/src/core/openjph/ojph_mem.h:47,
0.814                  from /OpenJPH/src/core/codestream/ojph_codestream_local.cpp:42:
0.814 /OpenJPH/src/core/openjph/ojph_arch.h:397:22: note: candidate: 'ojph::ui16 ojph::swap_bytes_if_le(ojph::ui16)'
0.814   397 |   static inline ui16 swap_bytes_if_le(ui16 t)
0.814       |                      ^~~~~~~~~~~~~~~~
0.814 /OpenJPH/src/core/openjph/ojph_arch.h:420:22: note: candidate: 'ojph::ui32 ojph::swap_bytes_if_le(ojph::ui32)'
0.814   420 |   static inline ui32 swap_bytes_if_le(ui32 t)
0.814       |                      ^~~~~~~~~~~~~~~~
0.814 /OpenJPH/src/core/openjph/ojph_arch.h:434:22: note: candidate: 'ojph::ui64 ojph::swap_bytes_if_le(ojph::ui64)'
0.814   434 |   static inline ui64 swap_bytes_if_le(ui64 t)
0.814       |                      ^~~~~~~~~~~~~~~~
```

This can be reproduce with the following `Dockerfile`:

```Dockerfile
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y cmake gcc g++ git

RUN git clone https://github.com/aous72/OpenJPH

WORKDIR /OpenJPH/build

RUN cmake -DCMAKE_BUILD_TYPE=Release -DOJPH_BUILD_TESTS=ON ..

RUN make
```

**Comment by aous72** [comment]
Thank you for posting this issue. 
It should have been fixed in bd091deba91acf709fd40b87062049959ba6d8fc.

Kind regards,
Aous.
